### ISSUE TITLE
Submodules return an error

### ISSUE THREAD

**Issue by SergioMendolia** [onigoetz/absorption#4]
```
Scanning █████████████████████████████████░░░░░░░ | 81% | 1968/2417 filesFailed item in queue Error: Command failed with exit code 128: git blame --incrementa
fatal: pas de chemin virtualization/drifter dans master
    at makeError (/usr/local/lib/node_modules/absorption/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/usr/local/lib/node_modules/absorption/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getBlame (/usr/local/lib/node_modules/absorption/src/git.js:66:3) {
  shortMessage: 'Command failed with exit code 128: git blame --incremental virtualization/drifter master',
  command: 'git blame --incremental virtualization/drifter master',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'fatal: pas de chemin virtualization/drifter dans master',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by onigoetz** [comment]
Hé merci :)

I’ll fix it tonight.
What would you expect to happen, scan the submodule as well or ignore it ?

**Comment by SergioMendolia** [comment]
I would probably ignore it. Also if it fails on a submodule, it might fail on git-LFS pointers too... I'll have a look

**Comment by SergioMendolia** [comment]
It doesn't :)
